#ifndef HIGHLIGHT_DIALOG_HPP
#define HIGHLIGHT_DIALOG_HPP

#include <QDialog>
#include <QList>
#include <QColor>
#include "HighlightRule.hpp"

// Forward declaration of the UI class generated by uic
namespace Ui {
class HighlightDialog;
}

class HighlightDialog : public QDialog
{
    Q_OBJECT

public:
    explicit HighlightDialog(QWidget *parent = nullptr);
    ~HighlightDialog();

    // Method to set the initial rules when opening the dialog
    void setHighlightRules(const QList<HighlightRule> &rules);

    // Method to get the final rules when the dialog is accepted
    QList<HighlightRule> getHighlightRules() const;

private slots:
    void on_buttonAddRule_clicked();
    void on_buttonChooseColor_clicked();
    void on_buttonEditRule_clicked();
    void on_buttonRemoveRule_clicked();
    void on_listWidgetRules_itemSelectionChanged();

private:
    void populateListWidget();
    void updateButtonStates();
    void updateColorButtonAppearance();
    void displayRuleInList(const HighlightRule &rule);

    Ui::HighlightDialog *ui;
    QList<HighlightRule> m_rules;
    QColor m_currentColor; // To store the currently selected color for adding/editing
};

#endif // HIGHLIGHT_DIALOG_HPP